version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always
  poll:
    build: ./poll
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - poll-tier
    environment:
        REDISP: redis
    restart: always
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - back-tier
      - result-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: popeye
    restart: always
  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    environment:
        REDISW: redis
        DBW: db
    restart: always
  result:
    build: ./result
    environment:
        PORTR: 80
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: